export const GET_ROLES = 'GET_ROLES';
export const GET_CAPABILITIES = 'GET_CAPABILITIES';
export const CHANGE_ROLE_CAPABILITIES = 'CHANGE_ROLE_CAPABILITIES';
export const LOAD_NEW_ROLE = 'LOAD_NEW_ROLE';